import { NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { DEFAULT_BUDGETS, DEFAULT_CREDIT_CARD, DEFAULT_SETTINGS, EXPENSE_CATEGORIES, PAYMENT_METHODS } from './utils/constants'
import { autoCategorizeTransaction, calculateCategoryTotals, calculateCreditCardUsage, calculateDailySummary, calculateMonthlySummary, formatCurrency, generateBudgetWarnings } from './utils/finance'

const useStored = (k, fallback) => { const [v, setV] = useState(()=>JSON.parse(localStorage.getItem(k) || 'null') ?? fallback); const save=(n)=>{setV(n);localStorage.setItem(k,JSON.stringify(n))}; return [v,save] }
const today = new Date().toISOString().slice(0,10)
const samples = [ ['Coffee',4.5,'expense','Food','cash'],['Apple',3,'expense','Groceries','debit'],['Bus fare',2.5,'expense','Transportation','credit'],['Salary',2500,'income','Income','debit'],['Rent',900,'expense','Rent','debit'],['Phone bill',40,'expense','Bills','credit'] ].map((s,i)=>({id:crypto.randomUUID(),description:s[0],amount:s[1],type:s[2],category:s[3],paymentMethod:s[4],date:today,createdAt:new Date(Date.now()+i).toISOString()}))

function App(){
  const [transactions,setTransactions]=useStored('sw_transactions',samples)
  const [settings,setSettings]=useStored('sw_settings',DEFAULT_SETTINGS)
  const [budgets,setBudgets]=useStored('sw_budgets',DEFAULT_BUDGETS)
  const [creditCard,setCreditCard]=useStored('sw_credit',DEFAULT_CREDIT_CARD)
  const addOrUpdate=(tx)=>{const next=tx.id?transactions.map(t=>t.id===tx.id?tx:t):[{...tx,id:crypto.randomUUID(),createdAt:new Date().toISOString()},...transactions];setTransactions(next)}
  const del=(id)=>setTransactions(transactions.filter(t=>t.id!==id))
  return <div className='min-h-screen bg-slate-50'><nav className='sticky top-0 bg-white border-b'><div className='max-w-6xl mx-auto p-3 flex gap-2 overflow-x-auto'>{['/','/add','/daily','/monthly','/credit','/goals','/settings'].map((p,i)=><NavLink key={p} to={p} className={({isActive})=>`px-3 py-2 rounded-lg text-sm whitespace-nowrap ${isActive?'bg-indigo-600 text-white':'bg-slate-100'}`}>{['Home','Add Transaction','Daily','Monthly','Credit Card','Goals','Settings'][i]}</NavLink>)}</div></nav>
  <main className='max-w-6xl mx-auto p-4'><Routes>
    <Route path='/' element={<Home/>}/><Route path='/add' element={<Add transactions={transactions} addOrUpdate={addOrUpdate} del={del}/>}/><Route path='/daily' element={<Daily transactions={transactions} settings={settings}/>}/><Route path='/monthly' element={<Monthly transactions={transactions} settings={settings} budgets={budgets}/>}/><Route path='/credit' element={<Credit transactions={transactions} settings={settings} creditCard={creditCard} setCreditCard={setCreditCard}/>}/><Route path='/goals' element={<Goals budgets={budgets} setBudgets={setBudgets} transactions={transactions} settings={settings}/>}/><Route path='/settings' element={<Settings settings={settings} setSettings={setSettings}/>}/>
  </Routes></main></div>
}
const Card=({title,children})=><div className='bg-white rounded-2xl shadow-sm border p-4'><h3 className='font-semibold mb-2'>{title}</h3>{children}</div>
function Home(){ const nav=useNavigate(); return <div className='space-y-5'><h1 className='text-3xl font-bold'>SpendWise</h1><p className='text-slate-600'>Track spending instantly. Understand your money clearly.</p><p>SpendWise helps capture transactions quickly, auto-categorizes expenses, and gives daily/monthly insights.</p><button onClick={()=>nav('/add')} className='px-4 py-2 bg-indigo-600 text-white rounded-lg'>Start Tracking</button><div className='grid sm:grid-cols-2 lg:grid-cols-4 gap-4'>{['Fast expense entry','Auto-categorized purchases','Budget warnings','Monthly financial overview'].map((x)=><Card key={x} title={x}><p className='text-sm text-slate-600'>Focused tools designed for mobile and desktop.</p></Card>)}</div></div> }
function Add({transactions,addOrUpdate,del}){ const [edit,setEdit]=useState(null); const [f,setF]=useState({amount:'',description:'',type:'expense',date:today,paymentMethod:'cash',category:'Other'}); const onDesc=(v)=>setF(s=>({...s,description:v,category:autoCategorizeTransaction(v)})); const submit=(e)=>{e.preventDefault();addOrUpdate({...f,id:edit?.id,amount:Number(f.amount)});setEdit(null);setF({amount:'',description:'',type:'expense',date:today,paymentMethod:'cash',category:'Other'})}; return <div className='space-y-4'><Card title='Add Transaction'><form onSubmit={submit} className='grid sm:grid-cols-2 gap-3'>{['amount','description','date','category'].map(k=><input key={k} value={f[k]} onChange={e=>k==='description'?onDesc(e.target.value):setF({...f,[k]:e.target.value})} required className='border rounded-lg p-2' placeholder={k} type={k==='amount'?'number':'text'}/>)}<select className='border rounded-lg p-2' value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value='expense'>Expense</option><option value='income'>Income</option></select><select className='border rounded-lg p-2' value={f.paymentMethod} onChange={e=>setF({...f,paymentMethod:e.target.value})}>{PAYMENT_METHODS.map(p=><option key={p}>{p}</option>)}</select><button className='sm:col-span-2 bg-indigo-600 text-white rounded-lg p-2'>{edit?'Update':'Save'} Transaction</button></form></Card><Card title='Recent Transactions'>{transactions.slice(0,8).map(t=><div key={t.id} className='flex justify-between py-2 border-b text-sm'><span>{t.description} ({t.category})</span><span>{t.type==='expense'?'-':'+'}{t.amount.toFixed(2)} <button onClick={()=>{setEdit(t);setF(t)}} className='text-indigo-600 ml-2'>Edit</button><button onClick={()=>del(t.id)} className='text-rose-600 ml-2'>Delete</button></span></div>)}</Card></div> }
function Daily({transactions,settings}){ const [date,setDate]=useState(today); const [cat,setCat]=useState('all'); const [pay,setPay]=useState('all'); const s=calculateDailySummary(transactions,date); const filtered=s.transactions.filter(t=>(cat==='all'||t.category===cat)&&(pay==='all'||t.paymentMethod===pay)); const catData=Object.entries(calculateCategoryTotals(filtered)).map(([name,value])=>({name,value})); return <div className='space-y-4'><input type='date' value={date} onChange={e=>setDate(e.target.value)} className='border rounded-lg p-2'/><div className='grid grid-cols-2 lg:grid-cols-4 gap-3'>{[['Daily income',s.income],['Daily expenses',s.expenses],['Net balance',s.net],['Transactions',s.count]].map(([k,v])=><Card key={k} title={k}>{typeof v==='number'?formatCurrency(v,settings.currency):v}</Card>)}</div><div className='flex gap-2'><select onChange={e=>setCat(e.target.value)} className='border p-2 rounded'><option value='all'>All categories</option>{['Food','Groceries','Transportation','Rent','Bills','Entertainment','Electronics','Other','Income','Other Income'].map(x=><option key={x}>{x}</option>)}</select><select onChange={e=>setPay(e.target.value)} className='border p-2 rounded'><option value='all'>All payment methods</option>{PAYMENT_METHODS.map(x=><option key={x}>{x}</option>)}</select></div><Card title='Category breakdown'>{catData.length? <div className='h-72'><ResponsiveContainer><PieChart><Pie data={catData} dataKey='value' nameKey='name'>{catData.map((_,i)=><Cell key={i} fill={['#4f46e5','#14b8a6','#f59e0b','#ef4444','#6366f1','#84cc16','#06b6d4','#64748b'][i%8]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div>:'No data'}</Card></div> }
function Monthly({transactions,settings,budgets}){ const [month,setMonth]=useState(today.slice(0,7)); const s=calculateMonthlySummary(transactions,settings,month); const category=Object.entries(calculateCategoryTotals(s.monthTx)).map(([name,value])=>({name,value})); const daily=Object.entries(s.monthTx.filter(t=>t.type==='expense').reduce((a,t)=>{a[t.date]=(a[t.date]||0)+t.amount;return a},{})).map(([date,amount])=>({date:date.slice(8),amount})); const warnings=generateBudgetWarnings(s,budgets,settings); return <div className='space-y-4'><input type='month' value={month} onChange={e=>setMonth(e.target.value)} className='border rounded-lg p-2'/><div className='grid sm:grid-cols-2 lg:grid-cols-5 gap-3'>{[['Monthly income',s.income],['Monthly expenses',s.expenses],['Fixed costs',s.fixedCosts],['Remaining money',s.remaining],['Savings progress',s.savingsProgress]].map(([k,v])=><Card key={k} title={k}>{formatCurrency(v,settings.currency)}</Card>)}</div><div className='grid lg:grid-cols-2 gap-3'><Card title='Spending by category'><div className='h-64'><ResponsiveContainer><BarChart data={category}><XAxis dataKey='name'/><YAxis/><Tooltip/><Bar dataKey='value' fill='#4f46e5'/></BarChart></ResponsiveContainer></div></Card><Card title='Daily spending'><div className='h-64'><ResponsiveContainer><BarChart data={daily}><XAxis dataKey='date'/><YAxis/><Tooltip/><Bar dataKey='amount' fill='#0ea5e9'/></BarChart></ResponsiveContainer></div></Card></div><Card title='Largest expenses'>{s.monthTx.filter(t=>t.type==='expense').sort((a,b)=>b.amount-a.amount).slice(0,5).map(t=><div key={t.id} className='text-sm py-1'>{t.description}: {formatCurrency(t.amount,settings.currency)}</div>)}</Card>{warnings.map(w=><div key={w} className='bg-amber-100 border border-amber-300 rounded-lg p-3'>{w}</div>)}</div> }
function Credit({transactions,settings,creditCard,setCreditCard}){ const usage=calculateCreditCardUsage(transactions,creditCard); const month=useMemo(()=>today.slice(0,7),[]); const m=calculateMonthlySummary(transactions,settings,month); return <div className='space-y-4'><Card title='Credit Card Settings'><div className='grid sm:grid-cols-3 gap-3'>{[['limit','number'],['currentBalance','number'],['dueDate','date']].map(([k,t])=><input key={k} type={t} className='border rounded-lg p-2' value={creditCard[k]} onChange={e=>setCreditCard({...creditCard,[k]:e.target.value})}/>)}</div></Card><div className='grid sm:grid-cols-2 lg:grid-cols-4 gap-3'>{[['Credit limit',usage.limit],['Used amount',usage.used],['Remaining credit',usage.remaining],['Utilization %',usage.utilization]].map(([k,v])=><Card key={k} title={k}>{k.includes('%')?`${v.toFixed(1)}%`:formatCurrency(v,settings.currency)}</Card>)}</div>{usage.utilization>70&&<div className='bg-rose-100 border border-rose-300 rounded-lg p-3'>Warning: utilization above 70%</div>}{usage.spending>m.remaining&&<div className='bg-rose-100 border border-rose-300 rounded-lg p-3'>Warning: credit card spending is higher than remaining monthly income.</div>}<Card title='Credit card transactions'>{usage.creditTx.map(t=><div key={t.id} className='py-1 text-sm'>{t.date} — {t.description} ({formatCurrency(t.amount,settings.currency)})</div>)}</Card></div> }
function Goals({budgets,setBudgets,transactions,settings}){ const month=today.slice(0,7); const s=calculateMonthlySummary(transactions,settings,month); return <div className='space-y-4'><Card title='Goals and Budgets'><div className='grid sm:grid-cols-2 gap-3'>{[['dailyLimit','Daily spending limit'],['monthlyLimit','Monthly spending limit'],['savingsGoal','Savings goal']].map(([k,l])=><label key={k} className='text-sm'>{l}<input type='number' className='w-full border p-2 rounded mt-1' value={budgets[k]} onChange={e=>setBudgets({...budgets,[k]:Number(e.target.value)})}/></label>)}</div><div className='grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4'>{EXPENSE_CATEGORIES.map(c=><label key={c} className='text-sm'>{c}<input type='number' className='w-full border p-2 rounded mt-1' value={budgets.categoryBudgets[c]} onChange={e=>setBudgets({...budgets,categoryBudgets:{...budgets.categoryBudgets,[c]:Number(e.target.value)}})}/></label>)}</div></Card><Card title='Budget progress'>{Object.entries(budgets.categoryBudgets).map(([c,b])=>{const spent=transactions.filter(t=>t.type==='expense'&&t.category===c&&t.date.startsWith(month)).reduce((a,t)=>a+t.amount,0); const pct=b?Math.min((spent/b)*100,100):0; return <div key={c} className='mb-2'><div className='flex justify-between text-sm'><span>{c}</span><span>{formatCurrency(spent,settings.currency)} / {formatCurrency(b,settings.currency)}</span></div><div className='h-2 bg-slate-200 rounded'><div className={`h-2 rounded ${pct>100?'bg-rose-500':pct>80?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${Math.min(pct,100)}%`}}/></div></div>})}</Card>{s.expenses>budgets.monthlyLimit&&<div className='bg-rose-100 border border-rose-300 rounded-lg p-3'>Monthly spending above configured monthly limit.</div>}</div> }
function Settings({settings,setSettings}){ return <Card title='Settings'><div className='grid sm:grid-cols-2 gap-3'>{[['currency','text'],['monthlyIncome','number'],['taxEstimate','number'],['rent','number'],['bills','number'],['otherFixedCosts','number']].map(([k,t])=><label key={k} className='text-sm capitalize'>{k}<input type={t} className='w-full border p-2 rounded mt-1' value={settings[k]} onChange={e=>setSettings({...settings,[k]:t==='number'?Number(e.target.value):e.target.value})}/></label>)}</div><button className='mt-4 px-3 py-2 bg-rose-600 text-white rounded' onClick={()=>{localStorage.clear();location.reload()}}>Clear all data</button></Card> }

export default App
